repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-added-large-files
  - id: check-builtin-literals
  - id: check-case-conflict
  - id: check-toml
  - id: check-yaml
  - id: debug-statements
  - id: end-of-file-fixer
  - id: forbid-new-submodules
  - id: trailing-whitespace

- repo: https://github.com/psf/black
  rev: 23.1.0
  hooks:
  - id: black

- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.0.270
  hooks:
    - id: ruff

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.3.0
  hooks:
  - id: mypy
    files: src
    args: ["--pretty", "--show-error-codes"]
    additional_dependencies: [
        'nox',
        'pytest',
    ]
